In [ ]:
##LIST

List adalah jenis kumpulan data terurut (ordered sequence) dan merupakan satu variabel yang sering digunakan pada phyton. Serupa namun tak sama dengan array pada bahasa pemrograman lainnya. Bedanya, elemen list pada phyton tidak harus memiliki tipe data yang sama. Cukup mudah digunakan yaitu dengan menggunakan kurung siku dan elemen yang dipisahkan dengan koma.

Setiap dat di dalamnya dapat diakses dengan indeks yang dimulai dari 0.

Variabel : Lokasi penyimpanan yang dapat digunakan untuk menampung sebuah data atau informasi. Syarat penamaan variable :
  

1.  Karakter-karakter yang digunakan untuk penamaan variable adalah alpabhet, angka dan underscore.
2.  Karakter pertama variable harus berupa huruf atau garis bawah / underscore dan tidak bisa berupa angka.
1.  Nama sebuah variable tidak bisa menggunakan keyword atau reserved words dari bahasa phyton seperti for, if, dan lainnya.
2.  Karakter pada nama variable bersifat sensitif (case sensitif).







In [1]:
#Membuat variable
kalimat = 'ini adalah variable'
bilangan1 = 4
bilangan2 = 2.5
bilangan3 = True
bilangan4 = 1j + 4

In [3]:
a="mangga, apel, rambutan"
a

'mangga, apel, rambutan'

TIPE DATA 

5 Tipe data yaitu:


1.   Integer atau bilangan bulat.
2.   Float atau bilangan bulat.
1.   String atau kalimat.
2.   Boolean yang terdiri dari true ad false
1.   Complex yang merupakan bilangan kompleks.








In [ ]:
# Menampilkan tipe data 
print(type(kalimat))
print(tpe(bilangan1))
print(type(bilangan2))
print(type(bilangan3))
print(type(bilangan4))


In [ ]:
#contoh list
L1 = [1,4,2,13]
L1

[1, 4, 2, 13]

In [ ]:
print(type(L1))


<class 'list'>


In [ ]:
#menggunakan tipe data yang berbeda
L2 = ("a", "phyton", 3, 2+3j)
L2


In [ ]:
##menampilkan elemen dengan fungsi print
warna = ["biru","merah","kuning","hijau"]
print(warna[2])
print(warna[1:3])
print(warna[-3])


kuning
['merah', 'kuning']
merah


Sifat-sifat list 


In [ ]:
#Terurut atau ordered
print("memanggil list L1 dengan indeks urutan :", L1[0:3])

In [ ]:
#Bisa diganti atau mutable
L1[1]= 2
print(L1)

In [ ]:
#Dapat diindeks/slicing
L1 = [1, "dua", True, 2+3j]
print("slicing list L1 :", L1[3])

In [ ]:
#Dapat dijadikan duplikasi
L1 = [[1, "dua", True, 2+3j, 2+3j]
print("Duplikasi pada list L1:", L1)

Tuple adalah jenis dari struktur data yang tidak dapat diubah elemennya. Umumnya tuple digunakan untuk data yang bersifat sekali tulis, dan dapat dieksekusi lebih cepat. Tuple didefinisikan dengan kurung dan elemen yang dipisahkan dengan koma.

In [ ]:
#Contoh Tuple
T1=(1,"dua", True, 1+2)
print("ini adalah tuple", T1)

ini adalah tuple (1, 'dua', True, 3)


In [ ]:
#menampilkan tipe struktur data
type(T1)

tuple

In [ ]:
#buatlah list kalian sendiri dengan tiga tipe data minimal enam elemen

In [ ]:
T2 = ("desimal", 76.0, 3j+10, True, "graph")
print ("ini adalah tuple 2",T2)

ini adalah tuple 2 ('desimal', 76.0, (10+3j), True, 'graph')


In [ ]:
T4 = (13, 14, 15, 16, 17)
T4

(13, 14, 15, 16, 17)

In [ ]:
T5 = (66,88,00,55)
T5

(66, 88, 0, 55)

In [ ]:
T6 =T4 + T5
T6

(13, 14, 15, 16, 17, 66, 88, 0, 55)

In [ ]:
##String

In [ ]:
#Slicing pada string
A = "Belajar struktur data string"
print(A[:5])
print(A[3:])
print(A[-5:])
print(A[4:9])
print(A[7:16])

Belaj
ajar struktur data string
tring
jar s
 struktur


In [ ]:
print(A[1:])
print (A[0:27])
print(A[1:27])

elajar struktur data string
Belajar struktur data strin
elajar struktur data strin


In [ ]:
##Memodifikasi string

In [ ]:
#upper()
A. upper()


'BELAJAR STRUKTUR DATA STRING'

In [ ]:
#lower()
A. lower()

'belajar struktur data string'

In [ ]:
#strip()
z='rzl rdt p'


In [ ]:
#replace()
A. replace ('u', 'i')

'Belajar striktir data string'

In [ ]:
#split()
A. split()

['Belajar', 'struktur', 'data', 'string']

In [ ]:
##Menggabungkan string


In [ ]:
A= "Belajar struktur data string"
B= "Pejuang data 3.0"
A + "" + B

'Belajar struktur data stringPejuang data 3.0'

In [ ]:
C = "Fakultas sains dan teknologi terapan"
D = "Prodi Matematika"
C + "" + D 


'Fakultas sains dan teknologi terapanProdi Matematika'

In [ ]:
## Set

Set adalah kumpulan item bersifat unik tanpa urutan 


In [ ]:
#Contoh Set
S1 = {1, "dua", True, 2+3j}

In [ ]:
#tidak dapat diindeks/silcing

In [ ]:
#Dapat diijinkan duplikasi
S1 = {1, "dua", "dua", 2, 2+3j} 
print("duplikasi pada set S1:1",S1)

duplikasi pada set S1:1 {1, 'dua', 2, (2+3j)}


In [ ]:
ganjil = {1,3,5,7,9}
genap = {2,4,6,8,10}
prima = {1,3,5,7}

In [ ]:
#Union
print(ganjil.union(genap))

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [ ]:
#intersection
print(ganjil.intersection(prima))

{1, 3, 5, 7}


In [ ]:
##Dictionary


Dictionary pada phyton adalah kumpulan

In [ ]:
L2 = [3, 'tiga', False, 2000, 7.8]

In [ ]:
L2

[3, 'tiga', False, 2000, 7.8]

In [ ]:
D2 = {10: 'genap', 3+3j : 8, 5.5 : True}
print(D2)

{10: 'genap', (3+3j): 8, 5.5: True}


In [ ]:
L2[2]

False

In [ ]:
D2 = {10: 'genap', 3+3j : 8, 5.5 :True, 'list':L2}
print(D2)

{10: 'genap', (3+3j): 8, 5.5: True, 'list': [3, 'tiga', False, 2000, 7.8]}


In [ ]:
#Memaggil elemen berdasarkan key

In [ ]:
print("D2[10]=", D2[10])

D2[10]= genap


In [ ]:
print("D2[3+3j]=", D2[3+3j])

D2[3+3j]= 8


In [ ]:
K = {1: 'ganjil', 2: 'genap'}
print("K[1]=", K[1])
print("k[2]=", K[2])

K[1]= ganjil
k[2]= genap


In [ ]:
angka = -2
if angka > 0:
  print(angka,"adalah bilangan positif.")
  print(angka, "adalah bilangan negatif")

In [ ]:
if test expression:
    Body of if
else:
    body of else

SyntaxError: ignored

In [ ]:
#program disusun untuk mengecek apakah angka kurang dari 0 atau tidak

angka = 3

if angka >=0:
 print("bilangan lebih dari atau sama dengan 0")
else:
   print("bilangan kurang dari 0")


bilangan lebih dari atau sama dengan 0


In [ ]:
#untuk mengecek apakah dua buah angka sama atau tidak #dan menampilkan tulisan yang sesuai

a = 5
b = 5

if a==b:
  print("a dan b bernilai sama")
else :
  ("a dan b bernilai berbeda")

a dan b bernilai sama


In [ ]:
#untuk mengecek apakah perbandingan dua buah angka #dan menampilkan tulisan yang sesuai

#membaca dua angka 
bil1 = int(input("masukkan bilangan pertama: "))
bil2 = int (input("masukkan bilangan kedua: "))

#memilih bilangan yang lebih besar
if bil1>bil2:
  bil_lebih_besar = bil1
else :
  bil_lebih_besar = bil2

#menampilkan hasil 
print("bilangan yang lebih besar adalah:", bil_lebih_besar)


masukkan bilangan pertama: 2
masukkan bilangan kedua: 7
bilangan yang lebih besar adalah: 7


In [ ]:
#IF ELIF ELSE


In [ ]:
if test expression
  body of if
elif test expression
  body of elif 
else test expression
  body of else 

PRAKTIK MEMBUAT FUNGSI

In [ ]:
#Argumen default
def  angka2(a, b, c, d=4):
     print(a, b, c, d)

angka2(1, 2, 3, 4)
angka2(1, b=2, c=3, d=100)
angka2(1, 2, 3)

1 2 3 4
1 2 3 100
1 2 3 4


In [ ]:
def penjumlahan(x,y,z=None):
  if (z==None):
    return x+y
  else:
    return x+y+z

print(penjumlahan(1,2))
print(penjumlahan(1,2,3))

3
6


In [ ]:
def penjumlahan(x,y):
    return x+y

a = penjumlahan
a(1, 2)


3

LAMDA

In [ ]:
def suqare_sum(x,y):
  return x**2 + y**2
  

dengan lamda kita tidak perlu menggunakan def atau return, bahkan kita juga tidak perlu menuliskan namanya.

In [ ]:
lambda x,y : x**2 + y**2


<function __main__.<lambda>(x, y)>

MENGGUNAKAN LAMDA EXPRESSION

Lamda bisa memiliki lebih dari satu argumen atau parameter, tapi hanya bisa memiliki sat ekspresi atau isi

In [ ]:
greeting = lambda name: print(f"hello, {name}")


karna fungsi lambda tidak punya nama, jadi kita butuh variabel untuk menyimpannya.

Nanti saat kita mau panggil, kita tinggal tuliskan saja nama variabelnya seperti ini:

In [ ]:
greeting("Dian")
greeting("Ayu")

hello, Dian
hello, Ayu


Beberapa contoh penggunaan lambda

In [ ]:
#Fungsi lamda untuk menambahkan angka 10 kepada argument input
f = lambda x: x+10
val1 = f(5)
val2 = f(100)
print(val1,val2)


15 110


In [ ]:
#Fungsi lamda untuk mengalikan dua argument input dan menampilkan hasilnya
f = lambda x,y:x*y
val3 = f(2,10)
val4 = f(7,5)
print(val3,val4)

20 35


ANONYMOUS FUNCTION

In [ ]:
def say_hello(nama):
  print(f"hello(name), apa kabar?")

ucapin = say_hello(name)

NameError: ignored

EKSEKUSI LAMBDA SECARA LANGSUNG

Eksekusi lambda secara langsung kelebihan fungsi dibandingkan def adalah bisa kita eksekusi langsung

Contohnya

In [ ]:
(lambda x,y: x**2 + y**2)(4,6)

52

Mengapa harus memakai lambda


In [ ]:
bilangan = [10,2,8,7,5,4,3,11,0,1]
filtered_result = map (lambda x: x*x, bilangan)
print(list(filtered_result))

[100, 4, 64, 49, 25, 16, 9, 121, 0, 1]


In [ ]:
#Menentukan bilangan genap
genap = lambda x: x%2 == 0
list(filter(genap, range(11)))

[0, 2, 4, 6, 8, 10]

In [ ]:
ganjil = lambda x: x%2 == 1
list(filter(ganjil, range(11)))

[1, 3, 5, 7, 9]

Pengenalan Pandas DataFrame

In [ ]:
import pandas as pd

In [ ]:
#List Buah (string)
list_buah = ['Jeruk', 'Pepaya', 'Mangga', 'Rambutan', 'Leci', 'Nanas', 'Manggis']

#List Berat Buah(integer)
list_berat = [50, 800, 150, 10, 2, 300, 70]

#Membuat dataframe menggunakan Dua Buah list dengan Fungsi Zip
df = pd.DataFrame(list(zip(list_buah, list_berat)),
              columns =['Nama Buah', 'Berat Buah'])

df

               

Nama Buah  Berat Buah
0     Jeruk          50
1    Pepaya         800
2    Mangga         150
3  Rambutan          10
4      Leci           2
5     Nanas         300
6   Manggis          70

In [ ]:
#List Multidimensi (Nama, Usia)
st = [['Bejo', 25], ['Ari', 30],
       ['Asep', 36], ['Richard', 22]]

df = pd.DataFrame(st, columns =['Nama', 'Usia'])
df

Nama  Usia
0     Bejo    25
1      Ari    30
2     Asep    36
3  Richard    22

Membuat dataframe menggunakan dictionary

In [ ]:
mobil = {'Type Mobil': ['Honda Civic', 'Toyota Corolla', 'Ford Focus', 'Audi A4'],
         'Harga(USD)': [22000, 25000,27000,35000]
         }

df = pd.DataFrame(mobil)

df

Type Mobil  Harga(USD)
0     Honda Civic       22000
1  Toyota Corolla       25000
2      Ford Focus       27000
3         Audi A4       35000

Import DataFrame dari file CSV 


In [ ]:
df_super_store = pd.read_csv()
df_super_store.head()

In [ ]:
df_pilkada=pd.read_excel('/content/datasetpilkadadki.xlsx')
df_pilkada.head()

Id Sentiment Pasangan Calon  \
0   1  negative     Agus-Sylvi   
1   2  negative     Agus-Sylvi   
2   3  negative     Agus-Sylvi   
3   4  negative     Agus-Sylvi   
4   5  negative     Agus-Sylvi   

                                          Text Tweet  
0  Banyak akun kloning seolah2 pendukung #agussil...  
1  #agussilvy bicara apa kasihan yaa...lap itu ai...  
2  Kalau aku sih gak nunggu hasil akhir QC tp lag...  
3  Kasian oh kasian dengan peluru 1milyar untuk t...  
4  Maaf ya pendukung #AgusSilvy..hayo dukung #Ani...

NumPy

In [ ]:
import numpy as np


Membuat Array NumPy
kita bisa membuat array menggunakan NumPy dengan membungkusnya terlebih dahulu di list dan dirubah menjadi numpy array

In [ ]:
list_1 = [1,2,3,4,5]
arr_1 = np.array([list_1])
arr_1

array([[1, 2, 3, 4, 5]])

In [ ]:
print(np.zeros((2,5))) # membuat array dengan nilai 0 dengan shape (5,5)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print(np.ones((5,3))) # membuat array dengan nilai 1 dengan shape (5,5)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.arange(1, 10, 2)) #arange(start, stop, step)

[1 3 5 7 9]


In [ ]:
print(np.linspace(1, 10, 2)) #linspace(start, stop, number)

[ 1. 10.]


In [ ]:
print(np.logspace(1, 10, 2)) # logspace(start,stop, number)

[1.e+01 1.e+10]


In [ ]:
print(np.full((2,2), 4)) # membuat array matriks dengan shape (2,2)

[[4 4]
 [4 4]]


In [ ]:
A = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(A)

print(np.full_like(A, 3)) # Membuat array matriks dengan shape yang sama dengan A dengan semua elemennya

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]]


In [ ]:
print(np.random.rand(4,2)) #Random ecimal number

[[0.87115009 0.29957937]
 [0.18157691 0.65985731]
 [0.98940855 0.74290067]
 [0.30403991 0.78437318]]


In [ ]:
print(np.random.randint(-4,8, size=(3,3))) #random integer values

[[-3 -2  7]
 [ 0  0  1]
 [-3 -1 -4]]


In [ ]:
print(np.identity(5)) #membuat matriks identitas

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr = np.array([[1,2,3]]) #membuat matriks dengan perulangan array
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
